# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ZommInButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZommInButton.setGeometry(QtCore.QRect(50, 530, 141, 41))
        self.ZommInButton.setObjectName("ZommInButton")
        self.ZommOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZommOutButton.setGeometry(QtCore.QRect(220, 530, 141, 41))
        self.ZommOutButton.setObjectName("ZommOutButton")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(460, 530, 251, 41))
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 661, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
    
        
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 657, 437))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.imgLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.imgLabel.setGeometry(QtCore.QRect(0, 0, 659, 439))
        # self.imgLabel.setObjectName("imgLabel")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        
        self.imgLabel = QtWidgets.QLabel()
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.imgLabel.setObjectName("imgLabel")
        self.scrollArea.setWidget(self.imgLabel)
        
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ZommInButton.setText(_translate("MainWindow", "Zoom In"))
        self.ZommOutButton.setText(_translate("MainWindow", "Zoom Out"))
        self.infoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.imgLabel.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
