# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        self.openFile.setGeometry(QtCore.QRect(80, 110, 121, 51))
        self.openFile.setObjectName("openFile")
        self.openFolder = QtWidgets.QPushButton(self.centralwidget)
        self.openFolder.setGeometry(QtCore.QRect(80, 290, 121, 51))
        self.openFolder.setObjectName("openFolder")
        self.fileText = QtWidgets.QTextEdit(self.centralwidget)
        self.fileText.setGeometry(QtCore.QRect(260, 110, 401, 81))
        self.fileText.setObjectName("fileText")
        self.folderText = QtWidgets.QTextEdit(self.centralwidget)
        self.folderText.setGeometry(QtCore.QRect(260, 290, 401, 81))
        self.folderText.setObjectName("folderText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFile.setText(_translate("MainWindow", "open file"))
        self.openFolder.setText(_translate("MainWindow", "open folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
